### ISSUE TITLE
Top Banner

### ISSUE THREAD

**Issue by briand44** [ITS-UofIowa/commencement.uiowa.edu#19]
Update top banner to resemble print design from OSC. Josh emailed this to all of us.

**Comment by adamdelaney** [comment]
I emailed OSC about this.

**Comment by adamdelaney** [comment]
> I’m out of the office today, but will briefly give you my thoughts and follow up tomorrow.

The seal can be used on this site, but shouldn’t be used in the header/site title. I could see it as a separate graphic in the main content area, but that is about it. If josh is wanting to match the program, I suggest just using Gotham for the header and that should be enough. 

I’ve got it watermarked on the interior pages of the program, which Josh hasn’t seen yet - but not sure how well that translates to web.

**Comment by adamdelaney** [comment]
> The university seal is reserved for official/presidential communication. It would be appropriate for the site to match the print documents in this case. However, we would not recommend using the seal for other website headers.
 
The seal is intended to be used in one color over a one-color solid field. The seal cannot be used in conjunction with the University of Iowa wordmark or any other graphic. It must be separated with a clear space, although both marks may certainly appear on the page. The seal can be used as a watermark and may only be cropped when used as a watermark. At this time, we do not have guidelines for minimum dimensions but we would ask that it be legible and recognizable.
 
I have copied Jess on this note since she designed the commencement print piece. She may have additional input. I am also attaching the seal as a vector graphic. You may also find additional information about the seal and secondary graphics here https://brand.uiowa.edu/secondary-graphics.

**Comment by adamdelaney** [comment]
Based upon Jessica's feedback we are not to implement the uiowa seal in the header. Closing this issue.
